# Generated by Django 2.2.7 on 2019-11-21 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='One_liner',
            fields=[
                ('one_liner_id', models.IntegerField(primary_key=True, serialize=False)),
                ('one_liner_text', models.TextField()),
                ('pub_date', models.DateField(verbose_name='one_liner date')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='created at date')),
                ('one_liner_count', models.IntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='one_liner.User')),
            ],
        ),
    ]
